#pragma once

#define FRAMEBUFFER_XRES 320
#define FRAMEBUFFER_YRES 240
#define FRAMEBUFFER_PIXEL (FRAMEBUFFER_XRES * FRAMEBUFFER_YRES)
#define FRAMEBUFFER_BYTES_PER_PIXEL 2 // 16-bit

#define WINDOW_XRES 320
#define WINDOW_YRES 240

#define WINDOW_REFRESH_RATE 20 // Window redraw rate in Hz