#pragma once

#define FRAMEBUFFER_XRES 320
#define FRAMEBUFFER_YRES 240
#define FRAMEBUFFER_PIXEL (FRAMEBUFFER_XRES * FRAMEBUFFER_YRES)
#define FRAMEBUFFER_BITS_PER_PIXEL 16
#define FRAMEBUFFER_BYTES_PER_PIXEL FRAMEBUFFER_BITS_PER_PIXEL >> 3
#define FRAMEBUFFER_BYTES (FRAMEBUFFER_PIXEL * FRAMEBUFFER_BYTES_PER_PIXEL)


#define WINDOW_XRES 320
#define WINDOW_YRES 240

#define WINDOW_REFRESH_RATE 20 // Window redraw rate in Hz